# Ubuntu Installation and WSL2 Hardening Script for IA Framework
# Installs Ubuntu 24.04 and configures optimal WSL2 settings
#
# Usage: Run from PowerShell as Administrator AFTER restarting from 01-install-wsl.ps1
#   .\tools\setup\windows\02-install-ubuntu-and-harden.ps1
#
# What this script does:
# - Verifies WSL2 features are enabled
# - Installs Ubuntu 24.04 LTS (with progress bar)
# - Creates optimized .wslconfig
# - Sets WSL2 as default version
# - Optionally adds Windows Defender exclusions
# - Shuts down WSL to apply settings

#Requires -RunAsAdministrator

Write-Host ""
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host "  IA Framework - Ubuntu Installation & WSL Hardening" -ForegroundColor Cyan
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host ""

# Function to check if Windows features are enabled
function Test-WindowsFeature {
    param([string]$FeatureName)

    $feature = Get-WindowsOptionalFeature -Online -FeatureName $FeatureName -ErrorAction SilentlyContinue
    return $feature -and $feature.State -eq "Enabled"
}

# Function to check if a WSL distribution is installed
function Test-WSLDistroInstalled {
    param([string]$DistroName)

    try {
        $distros = wsl --list --quiet 2>&1
        $distrosString = $distros -join "`n"
        return $distrosString -match $DistroName
    } catch {
        return $false
    }
}

# Function to get total system memory in GB
function Get-SystemMemoryGB {
    $totalMemory = (Get-CimInstance Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum).Sum
    return [Math]::Round($totalMemory / 1GB, 2)
}

# Function to calculate recommended WSL2 memory (50% of system RAM)
function Get-RecommendedWSLMemoryGB {
    $systemMemory = Get-SystemMemoryGB
    $recommended = [Math]::Floor($systemMemory * 0.5)
    return $recommended
}

# Function to create or update .wslconfig
function Set-WSLConfig {
    param(
        [int]$MemoryGB,
        [int]$Processors = 4,
        [int]$SwapGB = 8
    )

    $wslConfigPath = "$env:USERPROFILE\.wslconfig"
    $timestamp = Get-Date -Format "yyyy-MM-dd_HHmmss"

    # Backup existing .wslconfig if it exists
    if (Test-Path $wslConfigPath) {
        $backupPath = "$env:USERPROFILE\.wslconfig.backup_$timestamp"
        Copy-Item $wslConfigPath $backupPath
        Write-Host "  [OK] Backed up existing .wslconfig to: .wslconfig.backup_$timestamp" -ForegroundColor Green
    }

    # Create new .wslconfig content
    $wslConfig = @"
# WSL2 Configuration
# Generated by IA Framework setup on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
#
# These settings optimize WSL2 for development and container workloads
# while preventing memory overconsumption on Windows host.

[wsl2]
# Memory allocation (50% of system RAM)
memory=${MemoryGB}GB

# CPU cores for WSL2
processors=$Processors

# Swap space for memory overflow
swap=${SwapGB}GB

# Swap file location
swapfile=%USERPROFILE%\wsl-swap.vhdx

# Enable localhost forwarding (allows Windows to access WSL services)
localhostforwarding=true

# Enable nested virtualization (required for some container features)
nestedVirtualization=true

# Page reporting (helps reclaim unused memory)
pageReporting=true

# Kernel command line options
# kernelCommandLine =

"@

    # Write .wslconfig
    Set-Content -Path $wslConfigPath -Value $wslConfig -Force

    return $wslConfigPath
}

# Function to add Windows Defender exclusions
function Add-DefenderExclusions {
    Write-Host ""
    Write-Host "Step 4: Windows Defender Exclusions (Optional)" -ForegroundColor Cyan
    Write-Host "-----------------------------------------------"
    Write-Host ""
    Write-Host "Adding exclusions can improve performance but reduces security scanning." -ForegroundColor Gray
    Write-Host ""

    $addExclusions = Read-Host "Add Windows Defender exclusions? (y/N)"

    if ($addExclusions -eq 'y' -or $addExclusions -eq 'Y') {
        try {
            Write-Host ""
            Write-Host "  Adding exclusions..." -ForegroundColor Yellow

            # Add WSL2 virtual disk exclusion
            Add-MpPreference -ExclusionPath "$env:LOCALAPPDATA\Packages\CanonicalGroupLimited.Ubuntu*" -ErrorAction Stop
            Write-Host "  [OK] Excluded WSL2 virtual disk from scanning" -ForegroundColor Green

            # Add Docker Desktop exclusions if installed
            $dockerPath = "$env:ProgramFiles\Docker"
            if (Test-Path $dockerPath) {
                Add-MpPreference -ExclusionPath $dockerPath -ErrorAction Stop
                Write-Host "  [OK] Excluded Docker Desktop from scanning" -ForegroundColor Green
            }

            Write-Host "  [OK] Defender exclusions added successfully" -ForegroundColor Green

        } catch {
            Write-Host "  [WARN] Failed to add Defender exclusions: $_" -ForegroundColor Yellow
            Write-Host "  You may need to add these manually in Windows Security settings" -ForegroundColor Yellow
        }
    } else {
        Write-Host "  [CANCELLED] Skipping Defender exclusions" -ForegroundColor Gray
    }
}

# Main execution
Write-Host "Step 1: Verify WSL2 Features Are Enabled" -ForegroundColor Cyan
Write-Host "-----------------------------------------"
Write-Host ""

$wslEnabled = Test-WindowsFeature -FeatureName "Microsoft-Windows-Subsystem-Linux"
$vmEnabled = Test-WindowsFeature -FeatureName "VirtualMachinePlatform"

if (-not $wslEnabled -or -not $vmEnabled) {
    Write-Host "  [ERROR] WSL2 features are not enabled" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please run the first script to enable WSL2 features:" -ForegroundColor Yellow
    Write-Host '  Invoke-WebRequest -Uri "https://raw.githubusercontent.com/notchrisgroves/ia-framework/main/setup/windows/01-install-wsl.ps1" -OutFile "$env:TEMP\01-install-wsl.ps1"; & "$env:TEMP\01-install-wsl.ps1"' -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

Write-Host "  [OK] WSL2 features are enabled" -ForegroundColor Green

# Check if Ubuntu is already installed
if (Test-WSLDistroInstalled -DistroName "Ubuntu") {
    Write-Host "  [OK] Ubuntu distribution is already installed" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Skipping Ubuntu installation, proceeding to hardening..." -ForegroundColor Gray
    Write-Host ""
    $skipUbuntu = $true
} else {
    $skipUbuntu = $false
}

# Install Ubuntu if not already installed
if (-not $skipUbuntu) {
    Write-Host ""
    Write-Host "Step 2: Install Ubuntu 24.04 LTS" -ForegroundColor Cyan
    Write-Host "---------------------------------"
    Write-Host ""

    Write-Host "  Installing Ubuntu 24.04 (~500MB download)..." -ForegroundColor Yellow
    Write-Host "  You'll see a progress bar during download." -ForegroundColor Gray
    Write-Host ""

    try {
        # Install Ubuntu using wsl --install (progress shown by WSL)
        wsl --install -d Ubuntu-24.04

        if ($LASTEXITCODE -eq 0 -or $LASTEXITCODE -eq 3010) {
            Write-Host ""
            Write-Host "  [OK] Ubuntu 24.04 installed successfully" -ForegroundColor Green
        } else {
            Write-Host ""
            Write-Host "  [WARN] Installation may have issues (exit code: $LASTEXITCODE)" -ForegroundColor Yellow
            Write-Host "  Continuing with setup..." -ForegroundColor Gray
        }
    } catch {
        Write-Host ""
        Write-Host "  [ERROR] Failed to install Ubuntu: $_" -ForegroundColor Red
        Write-Host ""
        Write-Host "  Install manually:" -ForegroundColor Yellow
        Write-Host "    1. Open Microsoft Store" -ForegroundColor Yellow
        Write-Host "    2. Search for 'Ubuntu 24.04'" -ForegroundColor Yellow
        Write-Host "    3. Click 'Get' or 'Install'" -ForegroundColor Yellow
        Write-Host "    4. Run this script again" -ForegroundColor Yellow
        Write-Host ""
        exit 1
    }

    # Configure Windows to prevent Zone.Identifier files (registry)
    Write-Host ""
    Write-Host "  Configuring Zone.Identifier prevention..." -ForegroundColor Yellow

    try {
        $regPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments"
        if (!(Test-Path $regPath)) {
            New-Item -Path $regPath -Force | Out-Null
        }
        Set-ItemProperty -Path $regPath -Name "SaveZoneInformation" -Value 1 -Type DWord -Force
        Write-Host "    [OK] Registry fix applied (SaveZoneInformation=1)" -ForegroundColor Green
        Write-Host "    NOTE: /etc/wsl.conf will also be configured by Linux prerequisites script" -ForegroundColor Gray
    } catch {
        Write-Host "    [WARN] Could not apply registry fix: $_" -ForegroundColor Yellow
    }

    # Set WSL2 as default version
    Write-Host ""
    Write-Host "  Setting WSL2 as default version..." -ForegroundColor Yellow
    try {
        wsl --set-default-version 2 2>&1 | Out-Null
        Write-Host "  [OK] WSL2 set as default version" -ForegroundColor Green
    } catch {
        Write-Host "  [WARN] Could not set WSL2 as default" -ForegroundColor Yellow
    }
}

# Configure WSL2 settings
Write-Host ""
Write-Host "Step 3: Configure WSL2 Settings" -ForegroundColor Cyan
Write-Host "--------------------------------"
Write-Host ""

$systemMemory = Get-SystemMemoryGB
$recommendedMemory = Get-RecommendedWSLMemoryGB

Write-Host "  System Memory: $systemMemory GB" -ForegroundColor White
Write-Host "  Recommended WSL2 Memory: $recommendedMemory GB (50% of system RAM)" -ForegroundColor White
Write-Host ""

$procCount = (Get-CimInstance Win32_Processor).NumberOfLogicalProcessors
$recommendedProcs = [Math]::Max([Math]::Min($procCount - 2, 8), 2)

Write-Host "  System Processors: $procCount cores" -ForegroundColor White
Write-Host "  Recommended WSL2 Processors: $recommendedProcs cores" -ForegroundColor White
Write-Host ""

$confirm = Read-Host "Create .wslconfig with these settings? (Y/n)"

if ($confirm -eq 'n' -or $confirm -eq 'N') {
    Write-Host ""
    Write-Host "  [CANCELLED] Skipping .wslconfig creation" -ForegroundColor Gray
} else {
    $configPath = Set-WSLConfig -MemoryGB $recommendedMemory -Processors $recommendedProcs

    Write-Host ""
    Write-Host "  [OK] Created .wslconfig at: $configPath" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Settings:" -ForegroundColor White
    Write-Host "    - Memory: $recommendedMemory GB" -ForegroundColor White
    Write-Host "    - Processors: $recommendedProcs cores" -ForegroundColor White
    Write-Host "    - Swap: 8 GB" -ForegroundColor White
    Write-Host "    - Localhost forwarding: Enabled" -ForegroundColor White
    Write-Host "    - Nested virtualization: Enabled" -ForegroundColor White
}

# Defender exclusions (optional)
Add-DefenderExclusions

# Shutdown WSL to apply settings
Write-Host ""
Write-Host "Step 5: Apply WSL2 Settings" -ForegroundColor Cyan
Write-Host "---------------------------"
Write-Host ""

Write-Host "  Shutting down WSL to apply settings..." -ForegroundColor Yellow
try {
    wsl --shutdown
    Start-Sleep -Seconds 3
    Write-Host "  [OK] WSL shutdown complete" -ForegroundColor Green
} catch {
    Write-Host "  [WARN] Could not shutdown WSL: $_" -ForegroundColor Yellow
}

# Final instructions
Write-Host ""
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host "  [SUCCESS] Ubuntu Installation & Hardening Complete" -ForegroundColor Green
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Next steps:" -ForegroundColor White
Write-Host "  1. Open Ubuntu from the Start menu" -ForegroundColor White
Write-Host "     (First launch will complete setup - takes 1-2 minutes)" -ForegroundColor Gray
Write-Host "  2. Create your Ubuntu username and password when prompted" -ForegroundColor White
Write-Host "  3. Install prerequisites inside WSL by running:" -ForegroundColor White
Write-Host ""
Write-Host '     Invoke-WebRequest -Uri "https://raw.githubusercontent.com/notchrisgroves/ia-framework/main/setup/windows/03-install-prerequisites.ps1" -OutFile "$env:TEMP\03-install-prerequisites.ps1"; & "$env:TEMP\03-install-prerequisites.ps1"' -ForegroundColor Cyan
Write-Host ""
Write-Host "Optional: Install Docker Desktop (recommended for containers)" -ForegroundColor Yellow
Write-Host '  Invoke-WebRequest -Uri "https://raw.githubusercontent.com/notchrisgroves/ia-framework/main/setup/windows/04-install-docker.ps1" -OutFile "$env:TEMP\04-install-docker.ps1"; & "$env:TEMP\04-install-docker.ps1"' -ForegroundColor Yellow
Write-Host ""
