import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

export interface StyleState {
  colors: {
    primary: string;
    secondary: string;
    success?: string;
    warning?: string;
    danger?: string;
    info?: string;
    foreground?: string;
    background?: string;
    muted?: string;
    border?: string;
  };
  securityColors: {
    critical: string;
    high: string;
    medium: string;
    low: string;
    informational: string;
  };
  complianceColors?: {
    compliant?: string;
    partial?: string;
    nonCompliant?: string;
    na?: string;
    pending?: string;
  };
  tableColors?: {
    headerBg?: string;
    headerText?: string;
    stripe?: string;
    border?: string;
  };
  codeColors?: {
    bg?: string;
    text?: string;
    inlineBg?: string;
    inlineText?: string;
  };
  typography: {
    baseFamily: string;
    headingsFamily: string;
    monospaceFamily: string;
    baseSize?: string;
    lineHeight?: string;
    headingWeight?: string;
  };
}

const HEX_RE  = /^#[0-9A-Fa-f]{3,8}$/;
const RGB_RE  = /^rgba?\(\s*[\d.]+\s*,\s*[\d.]+\s*,\s*[\d.]+(\s*,\s*[\d.]+)?\s*\)$/;
const FONT_RE = /^[a-zA-Z0-9 ,'"_\-.]+$/;

function safeColor(v: string | undefined, fallback: string): string {
  if (!v) return fallback;
  if (HEX_RE.test(v) || RGB_RE.test(v)) return v;
  throw new Error(`Invalid color value: "${v}"`);
}

function safeFont(v: string | undefined, fallback: string): string {
  if (!v) return fallback;
  if (FONT_RE.test(v)) return v;
  throw new Error(`Invalid font family: "${v}"`);
}

export function generateStyles(state: StyleState): string {
  const { colors: c, securityColors: s, complianceColors: co = {},
          tableColors: t = {}, codeColors: cd = {}, typography: ty } = state;

  const nav  = safeColor(c.primary,       "#1F3B5C");
  const blue = safeColor(c.secondary,     "#4A90E2");
  const crit = safeColor(s.critical,      "#7C3AED");
  const high = safeColor(s.high,          "#DC2626");
  const med  = safeColor(s.medium,        "#EA580C");
  const low  = safeColor(s.low,           "#16A34A");
  const inf  = safeColor(s.informational, "#2563EB");

  const tableHeaderBg   = safeColor(t.headerBg,   nav);
  const tableHeaderText = safeColor(t.headerText,  "#FFFFFF");
  const tableStripe     = safeColor(t.stripe,      "#F8FAFC");
  const tableBorder     = safeColor(t.border,      "#E5E7EB");

  const codeBg       = safeColor(cd.bg,       "#0F172A");
  const codeText     = safeColor(cd.text,     "#E2E8F0");
  const codeInlineBg = safeColor(cd.inlineBg, "#F1F5F9");
  const codeInlineTx = safeColor(cd.inlineText, high);

  const compliant    = safeColor(co.compliant,    "#16A34A");
  const partial      = safeColor(co.partial,      "#EA580C");
  const nonCompliant = safeColor(co.nonCompliant, "#DC2626");
  const na           = safeColor(co.na,           "#6B7280");
  const pending      = safeColor(co.pending,      "#2563EB");

  return `/* IA Framework — styles.css (generated by css-writer) */
:root {
  --navy:        ${nav};
  --blue:        ${blue};
  --success:     ${safeColor(c.success,    "#16A34A")};
  --warning:     ${safeColor(c.warning,    "#EA580C")};
  --danger:      ${safeColor(c.danger,     "#DC2626")};
  --info:        ${safeColor(c.info,       "#2563EB")};
  --foreground:  ${safeColor(c.foreground, "#1E293B")};
  --background:  ${safeColor(c.background, "#FFFFFF")};
  --muted:       ${safeColor(c.muted,      "#6B7280")};
  --border:      ${safeColor(c.border,     "#E5E7EB")};

  --critical:    ${crit};
  --high:        ${high};
  --medium:      ${med};
  --low:         ${low};
  --informational:    ${inf};

  --compliant:     ${compliant};
  --partial:       ${partial};
  --non-compliant: ${nonCompliant};
  --na:            ${na};
  --pending:       ${pending};

  --table-header-bg:   ${tableHeaderBg};
  --table-header-text: ${tableHeaderText};
  --table-stripe:      ${tableStripe};
  --table-border:      ${tableBorder};

  --code-bg:        ${codeBg};
  --code-text:      ${codeText};
  --code-inline-bg: ${codeInlineBg};
  --code-inline-text: ${codeInlineTx};

  --font-base:      ${safeFont(ty.baseFamily,      "Inter, system-ui, -apple-system, sans-serif")};
  --font-headings:  ${safeFont(ty.headingsFamily,  "Outfit, system-ui, sans-serif")};
  --font-mono:      ${safeFont(ty.monospaceFamily, "'Fira Code', 'JetBrains Mono', Consolas, monospace")};
  --font-size:      ${ty.baseSize      ?? "0.95rem"};
  --line-height:    ${ty.lineHeight    ?? "1.65"};
  --heading-weight: ${ty.headingWeight ?? "700"};
}

body { font-family: var(--font-base); font-size: var(--font-size);
       line-height: var(--line-height); color: var(--foreground); }
h1,h2,h3,h4,h5,h6 { font-family: var(--font-headings); font-weight: var(--heading-weight); color: var(--navy); }
code, pre { font-family: var(--font-mono); }
pre { background: var(--code-bg); color: var(--code-text); padding: 1rem; border-radius: 6px; overflow-x: auto; }
code:not(pre > code) { background: var(--code-inline-bg); color: var(--code-inline-text); padding: .15em .4em; border-radius: 4px; font-size: .9em; }

table { border-collapse: collapse; width: 100%; margin-bottom: 1.5rem; }
thead th { background: var(--table-header-bg); color: var(--table-header-text); padding: .6rem 1rem; text-align: left; }
tbody tr:nth-child(even) { background: var(--table-stripe); }
tbody td { padding: .55rem 1rem; border-bottom: 1px solid var(--table-border); }

.badge-critical,.badge-high,.badge-medium,.badge-low,.badge-info,.badge-remediated {
  display:inline-block;padding:.2em .6em;border-radius:20px;font-size:.75rem;font-weight:700;text-transform:uppercase;color:#fff; }
.badge-critical   { background: var(--critical); }
.badge-high       { background: var(--high); }
.badge-medium     { background: var(--medium); }
.badge-low        { background: var(--low); }
.badge-info       { background: var(--informational); }
.badge-remediated { background: var(--informational); }

.finding-critical,.finding-high,.finding-medium,.finding-low,.finding-remediated {
  padding:1rem 1.25rem;margin-bottom:1rem;border-radius:0 6px 6px 0;border-left:5px solid; }
.finding-critical   { background:#F5F3FF; border-left-color: var(--critical); }
.finding-high       { background:#FEF2F2; border-left-color: var(--high); }
.finding-medium     { background:#FFF7ED; border-left-color: var(--medium); }
.finding-low        { background:#F0FDF4; border-left-color: var(--low); }
.finding-remediated { background:#EFF6FF; border-left-color: var(--informational); opacity:.8; }

.status-compliant     { color: var(--compliant);     font-weight: 600; }
.status-partial       { color: var(--partial);       font-weight: 600; }
.status-non-compliant { color: var(--non-compliant); font-weight: 600; }
.status-na            { color: var(--na);            font-weight: 600; }
.status-pending       { color: var(--pending);       font-weight: 600; }

/* ── Priority badges ─────────────────────────────────────────────────────────── */
.priority-immediate,.priority-short-term,.priority-medium-term,.priority-long-term,.priority-accepted {
  display:inline-block;padding:.2em .6em;border-radius:4px;font-size:.75rem;font-weight:700;text-transform:uppercase; }
.priority-immediate   { background: var(--critical); color:#fff; }
.priority-short-term  { background: var(--high);     color:#fff; }
.priority-medium-term { background: var(--medium);   color:#fff; }
.priority-long-term   { background: var(--low);      color:#fff; }
.priority-accepted    { background: var(--na);       color:#fff; }

/* ── Risk badges ─────────────────────────────────────────────────────────────── */
.risk-critical,.risk-high,.risk-medium,.risk-low,.risk-accepted {
  display:inline-block;padding:.2em .6em;border-radius:20px;font-size:.75rem;font-weight:700;text-transform:uppercase;color:#fff; }
.risk-critical { background: var(--critical); }
.risk-high     { background: var(--high); }
.risk-medium   { background: var(--medium); }
.risk-low      { background: var(--low); }
.risk-accepted { background: var(--na); }

/* ── Report structure ────────────────────────────────────────────────────────── */
.report-header {
  background: linear-gradient(135deg, var(--navy) 0%, color-mix(in srgb, var(--navy) 65%, black) 100%);
  color:#fff; padding:2.5rem 2rem; border-radius:8px; margin-bottom:2rem; }
.report-header h1 { color:#fff; margin-bottom:.15rem; border:none; }
.report-target { display:block; font-size:1.05rem; font-weight:400; opacity:0.8; margin-bottom:.75rem; color:#fff; }
.report-header-meta {
  display:flex; flex-wrap:wrap; gap:.75rem 2rem; margin-top:1rem; font-size:.9rem; }
.report-header-meta span { display:flex; gap:.35rem; align-items:baseline; }
.meta-label { font-weight:700; text-transform:uppercase; font-size:.7rem; letter-spacing:.05em; opacity:.8; }

.classification-notice {
  text-align:center; font-weight:700; font-size:.85rem; letter-spacing:.1em;
  padding:.4rem 1rem; border-radius:4px; margin-bottom:1.5rem; border:1px solid; }
.classification-notice.confidential { background:#FEF2F2; color:var(--high); border-color:var(--high); }
.classification-notice.restricted   { background:#FEF2F2; color:var(--high); border-color:var(--high); }
.classification-notice.internal     { background:#FFF7ED; color:var(--medium); border-color:var(--medium); }
.classification-notice.public       { background:#F0FDF4; color:var(--low); border-color:var(--low); }

.report-meta table { margin-bottom:0; }

/* ── Quarto callout overrides ────────────────────────────────────────────────── */
.callout-important { border-left-color: var(--critical) !important; }
.callout-important > .callout-header { background-color:#F5F3FF !important; }
.callout-warning   { border-left-color: var(--high) !important; }
.callout-warning   > .callout-header { background-color:#FEF2F2 !important; }
.callout-caution   { border-left-color: var(--medium) !important; }
.callout-caution   > .callout-header { background-color:#FFF7ED !important; }
.callout-tip       { border-left-color: var(--low) !important; }
.callout-tip       > .callout-header { background-color:#F0FDF4 !important; }
.callout-note      { border-left-color: var(--informational) !important; }
.callout-note      > .callout-header { background-color:#EFF6FF !important; }

/* ── Print ───────────────────────────────────────────────────────────────────── */
@media print {
  *, *::before, *::after {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  #quarto-sidebar, #quarto-sidebar-toggle, #quarto-margin-sidebar,
  .quarto-navigation, .navbar, #quarto-header { display:none !important; }
  #quarto-content, main#quarto-document-content,
  .quarto-main, #quarto-document-content {
    width:100% !important; max-width:100% !important;
    margin:0 !important; padding:0 !important;
  }
  h1, h2, h3 { page-break-after:avoid; }
  table       { page-break-inside:avoid; }
  @page       { margin:1in; }
}
`;
}

export function generateScss(state: StyleState): string {
  const { colors: c, securityColors: s, typography: ty } = state;
  return `/*-- scss:defaults --*/
$primary:   ${safeColor(c.primary,   "#1F3B5C")};
$secondary: ${safeColor(c.secondary, "#4A90E2")};
$success:   ${safeColor(c.success,   "#16A34A")};
$warning:   ${safeColor(c.warning,   "#EA580C")};
$danger:    ${safeColor(c.danger,    "#DC2626")};
$info:      ${safeColor(c.info,      "#2563EB")};
$body-color: ${safeColor(c.foreground, "#1E293B")};
$body-bg:    ${safeColor(c.background, "#FFFFFF")};

$font-family-sans-serif: ${safeFont(ty.baseFamily,      "Inter, system-ui, -apple-system, sans-serif")};
$font-family-monospace:  ${safeFont(ty.monospaceFamily, "'Fira Code', 'JetBrains Mono', Consolas, monospace")};
$headings-font-family:   ${safeFont(ty.headingsFamily,  "Outfit, system-ui, sans-serif")};
$font-size-base:         ${ty.baseSize      ?? "0.95rem"};
$line-height-base:       ${ty.lineHeight    ?? "1.65"};
$headings-font-weight:   ${ty.headingWeight ?? "700"};

/*-- scss:rules --*/
/* Security severity variables */
:root {
  --critical: ${safeColor(s.critical,      "#7C3AED")};
  --high:     ${safeColor(s.high,          "#DC2626")};
  --medium:   ${safeColor(s.medium,        "#EA580C")};
  --low:      ${safeColor(s.low,           "#16A34A")};
  --informational: ${safeColor(s.informational, "#2563EB")};
}
`;
}

export function writeStyleFiles(state: StyleState, frameworkRoot: string): string[] {
  const assetsDir = join(frameworkRoot, "private", "brand", "assets");
  mkdirSync(assetsDir, { recursive: true });

  const cssPath  = join(assetsDir, "styles.css");
  const scssPath = join(assetsDir, "theme-light.scss");

  writeFileSync(cssPath,  generateStyles(state), "utf-8");
  writeFileSync(scssPath, generateScss(state),   "utf-8");

  return [cssPath, scssPath];
}
